# Generated by Django 4.2.6 on 2023-12-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='quantity_change',
            field=models.IntegerField(verbose_name='Изменение количества'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Временная метка'),
        ),
    ]
