# Generated by Django 4.2.6 on 2023-12-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_material_name_alter_material_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='materialtransaction',
            options={'verbose_name_plural': 'Транзакция материалов'},
        ),
    ]
