# Generated by Django 4.2.6 on 2023-12-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('kroy_no', models.IntegerField(verbose_name='Крой номер')),
                ('ras_tkani', models.FloatField(verbose_name='Расход ткани')),
                ('ras_dublerin', models.FloatField(verbose_name='Расход дублерин')),
                ('edinitsa', models.IntegerField(blank=True, null=True, verbose_name='Единица')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name_plural': 'Крой',
            },
        ),
    ]
