# Generated by Django 4.2.6 on 2024-01-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uchastok_masterdata_kroy_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uchastok',
        ),
    ]
